version: "3.8"

services:
  cac_postgres:
    image: postgres:16-alpine
    container_name: cac_postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cac_app
    volumes:
      - cac_postgres:/var/lib/postgresql/data
      - ./src/creations.sql:/docker-entrypoint-initdb.d/init.sql

  cac_pgadmin:
    image: dpage/pgadmin4
    container_name: cac_pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - cac_pgadmin:/var/lib/pgadmin
    depends_on:
      - cac_postgres
  
  cac_backend:
    image: cac_backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cac_backend
    volumes:
      - ./src/static:/app/static
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - cac_postgres
      
networks:
  default:
    name: cac_sql

volumes:
  cac_postgres:
  cac_pgadmin: